filebeat.modules:
  - module: system
    syslog:
      enabled: true
      var.paths: ["/var/log/syslog*"]
  - module: system
    auth:
      enabled: true
      var.paths: ["/var/log/auth.log*"]
output.logstash:
  hosts: ["logstash:5044"]
setup.kibana:
  host: "<http://kibana:5601>"