filebeat.inputs:
  - type: filestream
    id: docker-filestream
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log

output.logstash:
  hosts: ["logstash:5044"]  

monitoring.enabled: false
logging.level: info
